# Generated by Django 6.0.7 on 2026-08-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='data',
            new_name='date',
        ),
    ]
